### ISSUE TITLE
Question about PCA9685 compatibility

### ISSUE THREAD

**Issue by BillionXP** [timhendriks93/blender-servo-animation#1]
I olny have a quite basic question. Does this work with pca9685 and is there a tutorial to set it up with the pca9685?

**Comment by timhendriks93** [comment]
Hi BillionXP, you opened this "issue" within the repository for the Blender Add-on, but there is also a repository with a compatible Arduino library. There I actually have 2 examples which show how to use the library with one or multiple PCA9685:

- https://github.com/timhendriks93/blender-servo-animation-arduino/tree/v1.2.0/examples/AdafruitPCA9685
- https://github.com/timhendriks93/blender-servo-animation-arduino/tree/v1.2.0/examples/MultiplePCA9685

The examples use exported data from this .blend file: https://github.com/timhendriks93/blender-servo-animation/tree/main/examples/IK

Once you have set up the Arduino example, you can open this file in Blender and make adjustments to the animation. Afterwards you can export the animation data again and update the respective ik.h file in your Arduino sketch.

I hope this helps, please let me know if you are missing anything else :)
